Add 3DES and file support to des.py
mbrown1413/des pull request #1
Opened 2019-06-23 16:31 UTC by elp2

python des.py -c 1234567890abcdef  d3001515557aadadd3001515557aadae
python des.py -d 161f79c6910b9c2d d3001515557aadadd3001515557aadae
-> 1234567890abcdef

2019-06-30 07:45 UTC, mbrown1413 commented
Sorry for the late response. I'm out of town at the moment, but I will look at this next week.

2019-07-12 16:05 UTC, mbrown1413 requested changes
Hi @elp2,

Thanks for waiting, and thanks for the new features! I like how it automatically detects the keying method based on the length.

I've made a few comments in a review. There is a small problem with how the results from each round are passed to the next round.

2019-07-12 16:05 UTC, mbrown1413 commented on des.py
> +            log(bits)
Avoid printing/logging extra information like intermediate results.
```suggestion
```

2019-07-12 16:05 UTC, mbrown1413 commented on des.py
> +                result += dsa_encrypt(t, key)
The same value for `text` is used for each round here, but each round should start with the previous round's result.

2019-07-12 16:05 UTC, mbrown1413 commented on des.py
> +            print bittools.bits_to_hex(result)
You can unindent this whole block of code that prints/outputs the results, so only the result of the final round is shown.

2019-12-15 23:31 UTC, elp2 commented on des.py
> +                result += dsa_encrypt(t, key)
Nice catch!

2019-12-16 04:04 UTC, elp2 reviewed
Double checked the encryption / decryption. Example:

python des.py -c 6173636963687273 0123456789abcdef00000000000000001111111111111111
32709d10300c0ed8
python des.py -d 32709d10300c0ed8 0123456789abcdef00000000000000001111111111111111
6173636963687273

2019-12-16 04:17 UTC, elp2 commented on des.py
> +            log(bits)
Fixed in round 2

2019-12-16 04:17 UTC, elp2 reviewed
Not sure if I resolved the log(bits) properly in #1. Looks good now in #2.

2020-01-15 23:15 UTC, mbrown1413 commented
Thanks for all this! It all looks good now, including your other PRs. Python 3 has been out for so long it feels weird to see xrange.

2020-01-15 23:15 UTC, merged